# Generated by Django 5.2.1 on 2025-05-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmeticapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
