# Generated by Django 5.2.1 on 2025-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmeticapp', '0002_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
